### ISSUE TITLE
Strict mode warning

### ISSUE THREAD

**Issue by Thernys** [ihor/Nspl#1]
With E_STRICT enabled, the inclusion of your library produces the following warning:

Strict Standards:  Declaration of nspl\ds\DefaultArray::fromArray() should be compatible with nspl\ds\ArrayObject::fromArray(array $array) in ...\vendor\ihor\nspl\nspl\ds\DefaultArray.php on line 70

**Comment by ihor** [comment]
Thanks for reporting this issue. It is fixed in the latest version. I'm not making any patch-release since it was introduced in a dev branch.
