### ISSUE TITLE
Allow functions to work with strings

### ISSUE THREAD

**Issue by ghost** [ihor/Nspl#11]
Strings are treatable as lists of characters. Having functions such as `with`, `map`, `ChainableSequence`, and so on support strings, makes it easy to loop over them or perform other operations on them.

Converting a string to an array is straightforward:

```php
$charList = [];

for ($i = 0; $i < mb_strlen($yourString); ++$i) {
    $charList[] = mb_substr($yourString[$i], $i, 1);
}
```

This should also support Unicode characters. Optionally, if you want to treat strings as a list of bytes (I would not make this the default, though, since it's not intuitive):

```php
$byteList = [];

for ($i = 0; $i < strlen($yourString); ++$i) {
    $byteList[] = $yourString[$i];
}
```

Thanks!

**Comment by ihor** [comment]
We would need to convert the result value back to string each time, which doesn't make much sense. One can convert string to an array on their own if needed:

```php
$string = with(str_split('hello world'))
    ->map(function($char) {
        if (in_array($char, ['a', 'e', 'i', 'o', 'u'])) {
            return strtoupper($char);
        }

        return $char;
    })
    ->reduce(\nspl\op\concat);
```

**Comment by ghost** [comment]
Doh, I forgot that `str_split` already exists.

In any case, it was not my intention to have the result convert back to a string automatically, but your proposed solution solves that elegantly, too, thanks!

Now I just need implicit cast operator overloads in PHP so I can have my strings coerce to arrays automatically without requiring `str_split` 😄...

EDIT: In case anyone's wondering, there currently is no Unicode-safe variant of `str_split`. There is `mb_split`, but it does something else. There are (cumbersome) ways to work around it, such as with `mb_split`, but you may be happy to hear `mb_str_split` [will be added in PHP 7.4](https://wiki.php.net/rfc/mb_str_split).
