### ISSUE TITLE
Best way to achieve partial application with operator functions

### ISSUE THREAD

**Issue by ghost** [ihor/Nspl#13]
`op` defines some useful function equivalents for operators, such as `sum`. Unfortunately, these don't take more than two arguments, which makes it impossible to partially apply an additional value into them. What would be the best solution to achieve this?

I've thought about allowing them to accept arbitrary arguments, but in the strictest sense they are correct as they are (most of them are monoids, after all).

Another solution may be to provide an additional function, like so:

```php
function infinitize(callable $function, int $arity): callable
{
    $looper = function (...$arguments) use (&$looper, $function, $arity) {
        $intermediateResult = $function(...array_slice($arguments, 0, $arity));
        $remainingArguments = array_slice($arguments, $arity);

        return $remainingArguments === [] ?
            $intermediateResult :
            $looper($intermediateResult, ...$remainingArguments);
    };

    return $looper;
}
```

This would allow making these functions infinite, for example:

```php
assert(infinitize(sum, 2)(1, 2, 3, 4, 5) === 15);
assert(rpartial(infinitize(sum, 2), 5)(1, 2, 3, 4) === 15);
```

But perhaps there already is an easier way to achieve this?

If not, feel free to pluck this function and pop it in the library if you want, it may need some additional exeption handling, in that case.

**Comment by ihor** [comment]
Could you please tell more about the use case? 

In the first example above I would do:
```php
assert(reduce(sum, [1, 2, 3, 4, 5], 0) === 15);
```

**Comment by ghost** [comment]
Thanks for your response.

The use case I originally have is to do something like `reduce`, but whilst concatenating all the strings, add an additional string in between between every concatenation (a bit like `implode` does).

What you can currently do:

```php
assert(reduce(concat, ['one', 'two', 'three'], '') === 'onetwothree');
```

What I want to achieve:

```php
assert(reduce(something_with(concat, ', '), ['one', 'two', 'three'], '') === 'one, two, three, ');
```

I cannot partially apply `concat`, because it only takes two parameters and doing that would make a new, unary function, which is no longer suitable to pass to `reduce`.

If, however, `concat` took an arbitrary amount of arguments, this problem would be solved. I would just be partially applying one of the infinite arguments and using that with `reduce` would still work, because the function can be binary. This is what `infinitize` does; it turns a binary function into an N-ary function that can fit the bill.

**Comment by ihor** [comment]
Something like that?
```php
$addComma = rpartial(concat, ',');

$string = with(['one', 'two', 'three'])
    ->map($addComma)
    ->reduce(concat, '');
```

**Comment by ghost** [comment]
Thanks, that indeed does the trick without requiring any sort of `infinitize`. I feel like I should have thought of your solution before inventing an overly complex solution like `infinitize`. Seeing simple solutions to simple problems doesn't appear to always be obvious to me yet whilst programming functionally.

Not sure if there is another use case for `infinitize`; perhaps it can be useful with the splat operator, though `reduce` with binary functions appears to be a suitable replacement for that usually, but I can't think of any functional ones right now, so out it goes 😉.

Thanks!
