### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by kodecraft** [ihor/Nspl#3]
I tried installing via

``` bash
$ composer require ihor/nspl (this was really retrieving ^1.0)
```

as suggested by the github documentation but was met with quite a few errors. I then updated to the latest "1.1.*-dev" code and the errors went away. Maybe the docs can be highlighted to use the latest version to save new users from thrashing about to get it to work since the api (at least for the nspl\args namepace) has changed quite a bit.

**Comment by ihor** [comment]
Thanks, this is very useful feedback. I added a link to the version `1.0.1` (last stable) documentation and plan to update the changelog with all changes made in `1.1.*-dev`.

**Comment by kodecraft** [comment]
tks!
